import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import {
  Tooltip,
  TooltipContent,
  TooltipProvider,
  TooltipTrigger,
} from "@/components/ui/tooltip";
import { techStack, TechCategory, TechItem } from "./tech"; // Import the data
import { TechIcon } from "@/components/custom/TechIcon"; // Import the new client component

export const metadata = {
  title: "Tech Stack | Soufiane Chaoufi",
  description:
    "Overview of the technologies, tools, and languages I use in software development.",
};

// Helper function to get icon path (handles different extensions)
// Note: This assumes icons exist after running the download script.
// It checks for common extensions based on the script's logic.
const getIconPath = (iconKey: string): string | null => {
  const basePath = `/tech-stack/${iconKey}`;
  // Check common extensions based on script logic and known types
  const extensions = [".svg", ".png", ".jpg", ".jpeg", ".gif", ".webp"];
  for (const ext of extensions) {
    // Simple check - ideally, we'd know the exact extension from the script/data
    // For now, just return the first likely path. A more robust solution
    // might involve the script outputting a manifest file.
    // Let's prioritize SVG and PNG as they are most common in the list.
    if (ext === ".svg" || ext === ".png") {
      // This is a simplified check. A real app might need fs access at build time
      // or a manifest file generated by the download script.
      // For now, we construct the path and hope it exists.
      return `${basePath}${ext}`;
    }
  }
  // Fallback for other extensions if needed, or return null
  // Returning the .svg path as a fallback based on original script behavior
  return `${basePath}.svg`;
};

export default function TechStackPage() {
  return (
    <div className="container mx-auto max-w-4xl py-12">
      <h1 className="mb-8 text-center text-3xl font-bold tracking-tight sm:text-4xl">
        My Tech Stack
      </h1>
      <p className="text-muted-foreground mb-12 text-center text-lg">
        The tools, languages, and frameworks I frequently use to build software.
      </p>

      <div className="grid grid-cols-1 gap-8 md:grid-cols-2">
        {techStack.map((category: TechCategory) => (
          <Card key={category.name}>
            <CardHeader>
              <CardTitle>{category.name}</CardTitle>
            </CardHeader>
            <CardContent>
              <TooltipProvider delayDuration={100}>
                <ul className="flex flex-wrap gap-4">
                  {category.items.map((item: TechItem) => {
                    const iconPath = item.icon ? getIconPath(item.icon) : null;
                    return (
                      <li key={item.name}>
                        <Tooltip>
                          <TooltipTrigger asChild>
                            {/* Container div for the tooltip trigger */}
                            <div className="bg-card hover:bg-accent hover:text-accent-foreground flex h-16 w-16 items-center justify-center rounded-lg border p-2 transition-colors">
                              {/* Use the TechIcon client component */}
                              <TechIcon item={item} iconPath={iconPath} />
                            </div>
                          </TooltipTrigger>
                          <TooltipContent>
                            <p>{item.name}</p>
                          </TooltipContent>
                        </Tooltip>
                      </li>
                    );
                  })}
                </ul>
              </TooltipProvider>
            </CardContent>
          </Card>
        ))}
      </div>
    </div>
  );
}
